version: "3.3"

services:
  transmission:
    image: linuxserver/transmission:version-3.00-r5
    container_name: transmission-test
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=test
      - PASS=test
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
